name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential sqlite3
      - name: build
        run: |
          autoreconf -vfi
          ./configure --enable-all
          make
          sudo make install
